### ISSUE TITLE
Make it easier to scrobble multiple tracks from one album

### ISSUE THREAD

**Issue by wolflambert** [elamperti/OpenWebScrobbler#28] opened 2017-05-12 16:16 UTC
I'd implement this using a button that locks the contents of a field.

**Comment by elamperti** [comment] 2017-05-12 16:31
Yes, that would be a good approach! Possible duplicate of #18 

Thanks for your suggestion! :)

**Comment by wolflambert** [comment] 2017-05-12 16:33
Oh, right. Feel free to merge. You're welcome!

**Closed** 2017-06-25 17:08 UTC
Labels: duplicate, feature
