### ISSUE TITLE
Scrobble entire album at a time?

### ISSUE THREAD

**Issue by demiters** [elamperti/OpenWebScrobbler#39] opened 2018-07-08 10:47 UTC
Would this be possible so one wouldn't have to enter songs one at a time?

**Comment by elamperti** [comment] 2018-07-08 18:08
Hi @demiters, it's coming soon! I'll let you know here when it's ready :)

Thanks for your suggestion!



(Duplicate of #13)

**Closed** 2018-07-08 18:08 UTC
Labels: duplicate, feature
